apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeaudit-frontend
  namespace: kubeaudit-revamp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeaudit-frontend
  template:
    metadata:
      labels:
        app: kubeaudit-frontend
    spec:
      containers:
        - name: frontend
          image: kubeaudit-revamp-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubeaudit-frontend
  namespace: kubeaudit-revamp
spec:
  selector:
    app: kubeaudit-frontend
  ports:
    - port: 80
      targetPort: 80

